services:
  flask:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - MYSQL_HOST
      - MYSQL_DB
      - MYSQL_USER
      - MYSQL_PASSWORD
      - SMTP_SENDER
      - SMTP_PASSWORD
      - USE_AI

  redis:
    image: redis:latest
    ports:
      - "6379:6379"