services:
  flask:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL
      - MYSQL_HOST
      - MYSQL_DB
      - MYSQL_USER
      - MYSQL_PASSWORD
      - SMTP_SENDER
      - SMTP_PASSWORD
      - USE_AI
    networks:
      - app-network

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "0.0.0.0"]
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
