"""fix chat_message contents length

Revision ID: 4b456645d5f8
Revises: f291e3860ade
Create Date: 2025-06-16 18:47:29.391472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b456645d5f8'
down_revision: Union[str, None] = 'f291e3860ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_data')
    op.alter_column('advogado', '_salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=29),
               existing_nullable=False)
    op.alter_column('requerente', '_salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=29),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requerente', '_salt',
               existing_type=sa.LargeBinary(length=29),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)
    op.alter_column('advogado', '_salt',
               existing_type=sa.LargeBinary(length=29),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.create_table('ai_data',
    sa.Column('id_data', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('positive_odd', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('partial_odd', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('negative_odd', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('id_demanda', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_demanda'], ['demanda.id_demanda'], name=op.f('ai_data_ibfk_1')),
    sa.PrimaryKeyConstraint('id_data'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
