"""add processo entity

Revision ID: 60df5ccb3038
Revises: 3b227cfa2678
Create Date: 2025-06-07 17:01:06.027772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60df5ccb3038'
down_revision: Union[str, None] = '3b227cfa2678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processo',
    sa.Column('numero_tjmg', sa.String(length=32), nullable=False),
    sa.Column('acordao', sa.Text(), nullable=False),
    sa.Column('ementa', sa.String(length=8192), nullable=False),
    sa.Column('sumula', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('numero_tjmg')
    )
    op.alter_column('advogado', '_salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=29),
               existing_nullable=False)
    op.alter_column('requerente', '_salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=29),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requerente', '_salt',
               existing_type=sa.LargeBinary(length=29),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)
    op.alter_column('advogado', '_salt',
               existing_type=sa.LargeBinary(length=29),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.drop_table('processo')
    # ### end Alembic commands ###
