"""add advogado_pfp

Revision ID: 8703e1774331
Revises: 0badb89e1c7f
Create Date: 2025-06-04 13:23:05.392315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8703e1774331'
down_revision: Union[str, None] = '0badb89e1c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processo')
    op.drop_table('ai_data')
    op.alter_column('advogado', '_salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=29),
               existing_nullable=False)
    op.alter_column('requerente', '_salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=29),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requerente', '_salt',
               existing_type=sa.LargeBinary(length=29),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)
    op.alter_column('advogado', '_salt',
               existing_type=sa.LargeBinary(length=29),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.create_table('ai_data',
    sa.Column('id_data', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('positive_odd', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('partial_odd', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('negative_odd', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('id_demanda', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_demanda'], ['demanda.id_demanda'], name=op.f('ai_data_ibfk_1')),
    sa.PrimaryKeyConstraint('id_data'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('processo',
    sa.Column('numero_tjmg', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('acordao', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('ementa', mysql.VARCHAR(length=8192), nullable=False),
    sa.Column('sumula', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('numero_tjmg'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
