"""change chat_message content lenth to LONGTEXT

Revision ID: fd5845d18b21
Revises: 4b456645d5f8
Create Date: 2025-06-16 18:53:45.954302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd5845d18b21'
down_revision: Union[str, None] = '4b456645d5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advogado', '_salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=29),
               existing_nullable=False)
    op.alter_column('chat_message', 'contents',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('requerente', '_salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=29),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requerente', '_salt',
               existing_type=sa.LargeBinary(length=29),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)
    op.alter_column('chat_message', 'contents',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('advogado', '_salt',
               existing_type=sa.LargeBinary(length=29),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
