name: Build and Run Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t jurai-web .
    - name: Run Docker container
      env:
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_DB: ${{ secrets.MYSQL_DB }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PWD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        docker run -d -p 8000:8000 --name flask-app \
        -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
        -e MYSQL_DB=${{ secrets.MYSQL_DB }} \
        -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
        -e MYSQL_PASSWORD=${{ secrets.MYSQL_PWD }} \
        -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
        jurai-web

    - name: Wait for app to start
      run: |
        sleep 15

    - name: Check application health
      run: |
        sleep 10
        curl -f http://localhost:8000/ || exit 1

    - name: Show uWSGI logs
      run: |
        docker logs flask-app

    - name: Stop and remove Docker container
      run: |
        docker stop flask-app
        docker rm flask-app
